### ISSUE TITLE
I lost my world

### ISSUE THREAD

**Issue by Maksi432** [AstralVixen/Steel-and-Sakura#1]
I played for 6-7 hours in my world, then installed this mod and uninstalled it (cuz it was too difficult)
And now I can't load my world at all. The game states that the world files are faulty.
When I loaded this mod back, the world started ._.

![Screenshot (65)](https://github.com/user-attachments/assets/43bb86d5-5f5e-486a-aedf-f8d31a4c32f7)
![Screenshot (66)](https://github.com/user-attachments/assets/a876af28-4a42-4cde-b7fe-927f69172a5d)

**Comment by AstralVixen** [comment]
That's not something I have encountered before. It's probably due to a structure in it (as it's a world data related bug) but I will have to experiment. 

Also could you please tell me what you found too difficult in the mod? I'm looking to balance it for the release update the best I can.

**Comment by Maksi432** [comment]
> That's not something I have encountered before. It's probably due to a structure in it (as it's a world data related bug) but I will have to experiment.
> 
> Also could you please tell me what you found too difficult in the mod? I'm looking to balance it for the release update the best i can.

In this mod, it was hard for me that NPCs break into my house uninvited and kill me.
So, I just prefer simpler gameplay.

I think you should prevent them from opening doors or spawning near the player's bed.

Can you write me all the mob names from this mod?
Maybe I'll try to kill them with the /kill and load the world without them

**Comment by AstralVixen** [comment]
Thank you for your feedback! I will be removing the door opening function or maybe make it into a config option in the next update.

As for mobs I doubt they are causing the issues I think it's a structure but since you mentioned it:
Try killing all the **yurei** mobs in your world since I accidentally disabled auto despawn for them.

**Comment by Maksi432** [comment]
I created a new world, i think it's better than previous.
When is the update? I like the setting of this mod and hope that will be more balanced. Maybe after the update I will download it back. 
Good luck with the mod development!
